# Generated by Django 5.2.15 on 2026-06-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clip_index", models.IntegerField()),
                ("start_sec", models.FloatField()),
                ("end_sec", models.FloatField()),
                ("caption", models.TextField(blank=True)),
                ("ocr_text", models.TextField(blank=True)),
                ("action_label", models.CharField(blank=True, max_length=150)),
                ("action_confidence", models.FloatField(blank=True, null=True)),
                ("actions_detected", models.JSONField(default=list)),
                ("objects_detected", models.JSONField(default=list)),
                ("ocr_blocks", models.JSONField(default=list)),
                ("caption_confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["video", "clip_index"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("indexed", "Indexed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("timestamp_sec", models.FloatField()),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyframes",
                        to="search.clip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndexingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress_pct", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("error_msg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="search.video",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clip",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clips",
                to="search.video",
            ),
        ),
    ]
